CREATE TABLE [CONTROL].[C_CONTROL_PROCESS_INSTANCE] (

	[CONTROL_PROC_INST_ID] int NOT NULL, 
	[CONTROL_PROC_ID] int NOT NULL, 
	[CONTROL_PROC_INST_START_DATETIME] datetime2(6) NOT NULL, 
	[CONTROL_PROC_INST_END_DATETIME] datetime2(6) NULL, 
	[CONTROL_PROC_INST_RUNNING_FLAG] int NOT NULL, 
	[CONTROL_PROC_INST_ERROR_FLAG] int NOT NULL
);